version: "3.8"

services:
  traefik:
    image: traefik:v3.0
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc/traefik:/etc/traefik
    restart: unless-stopped
