entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
    proxyProtocol:
      # this is probably still ok. This just means that any incoming request
      # from HA Proxy will use the actual client IP instead of the proxys IP (I think)
      insecure: true

  web-secure:
    address: :443
    proxyProtocol:
      insecure: true
  
  gitea_ssh:
    address: :222

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false
  file:
    directory: /etc/traefik/file_providers

api:
  dashboard: true

certificatesResolvers:
  le:
    acme:
      email: riley@rileymathews.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

  cf:
    acme:
      email: riley@rileymathews.com
      storage: /etc/traefik/cfacme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53
